name: easy_localization_loader
description: Easy Localization Loader custom assets loaders for easy_localization (Json, CSV, http, Xml, API ...)
# author: AISSAT abdelwahab <mr.aissat@gmail.com>
homepage: https://github.com/aissat/easy_localization_loader
issue_tracker: https://github.com/aissat/easy_localization_loader/issues

version: 0.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  csv: ^4.0.3
  yaml: ^2.2.1
  xml: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

